# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-04 10:14
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('cause', models.CharField(blank=True, max_length=80, null=True)),
                ('str_addr', models.CharField(blank=True, max_length=18, null=True)),
                ('accid_num', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'accidents',
                'managed': True,
            },
        ),
    ]
