# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-04 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobalert', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accident',
            table='accident',
        ),
    ]
