# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-04 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobalert', '0002_auto_20190904_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accident',
            options={'managed': True},
        ),
    ]
