# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-10-21 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobalert', '0005_accpoints'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccPoints',
        ),
    ]
