# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-10-21 10:51
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobalert', '0007_accpoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccPointsBuffer',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.FloatField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=80, null=True)),
                ('distance', models.BigIntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'acc_points_buffer',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AccPoints',
        ),
    ]
